server:
  port: 8089
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test_es?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/test_es?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
